spring:
  datasource:
    url: jdbc:mysql://112.124.45.181:3306/HIS?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: d04156197c455db0
    # ???
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      max-active: 16
      min-idle: 1
      max-wait: 60000
  redis:
    database: 1       # 指定所在的库
    host: 112.124.45.181   # Redis服务器地址 写你的ip
    port: 6379        # Redis服务器连接端口
    password: lq8.2357  # Redis服务器连接密码
    lettuce:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）  类似于mysql的连接池
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制） 表示连接池的链接拿完了 现在去申请需要等待的时间
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
    timeout: 6000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl